#!/usr/bin/env python3
# -*- coding: utf-8 -*-

print("🧪 PromptBook 빠른 테스트 가이드")
print("=" * 50)
print()

print("📋 클립보드 기능 테스트:")
print("1. 페이지 선택 → Ctrl+C (복사)")
print("2. 다른 북 선택 → Ctrl+V (붙여넣기)")
print("3. 페이지 선택 → Ctrl+X (잘라내기)")
print("4. 다른 북 선택 → Ctrl+V (붙여넣기)")
print()

print("⌨️ 키보드 단축키 테스트:")
print("- Ctrl+N: 새 북 생성")
print("- Ctrl+Shift+N: 새 페이지 생성")
print("- Ctrl+D: 복제")
print("- Delete: 삭제")
print("- F2: 이름 변경")
print("- Ctrl+F: 검색")
print("- F11: 전체화면")
print("- Ctrl+T: 테마 변경")
print()

print("🖱️ 우클릭 메뉴 테스트:")
print("- 북 우클릭: 새 페이지, 이름 변경, 복제, 삭제, 붙여넣기")
print("- 페이지 우클릭: 복제, 삭제, 이름 변경, 즐겨찾기, 잠금, 복사, 잘라내기")
print("- 이모지 우클릭: 이모지 변경")
print()

print("🔍 정렬 및 검색 테스트:")
print("- 오름차순/내림차순 정렬 버튼 클릭")
print("- 검색창에 키워드 입력")
print("- 즐겨찾기 토글 테스트")
print()

print("⚠️ 엣지 케이스 테스트:")
print("- 매우 긴 이름 입력해보기")
print("- 특수문자 포함 이름 (예: @#$%)")
print("- 빈 이름으로 저장 시도")
print("- 잠긴 페이지 편집 시도")
print("- 동일한 이름 중복 생성")
print()

print("💡 추천 테스트 시나리오:")
print("1. 새 북 생성 → 페이지 여러 개 추가 → 내용 입력")
print("2. 페이지 복사/잘라내기로 다른 북으로 이동")
print("3. 즐겨찾기 설정 후 정렬 확인")
print("4. 페이지 잠금 후 편집 시도")
print("5. 테마 변경 후 UI 확인")
print("6. 검색 기능으로 페이지 찾기")
print()

print("🎯 현재 상태 확인:")
print("- 프롬프트북이 실행 중입니다")
print("- 클립보드 기능 (Ctrl+C, Ctrl+X, Ctrl+V) 활성화됨")
print("- 드래그 앤 드롭은 현재 비활성화 상태")
print("- AI 테스터는 메뉴에서 '🤖 AI 기능 테스터' 클릭으로 접근 가능")
print()

print("=" * 50)
print("위의 기능들을 직접 프롬프트북에서 테스트해보세요!") 